### ISSUE TITLE
cargo crev crate verify panics and hangs on local unpublished crate

### ISSUE THREAD

**Issue by CAD97** [crev-dev/cargo-crev#272]
```cmd
D:\repos\cad97\pointer-utils>dir
 Volume in drive D is M.2 SATA
 Volume Serial Number is 363A-D7FB

 Directory of D:\repos\cad97\pointer-utils

2019-12-16  09:03 PM    <DIR>          .
2019-12-16  09:03 PM    <DIR>          ..
2019-12-16  09:00 PM                19 .gitignore
2019-12-17  02:12 PM    <DIR>          .idea
2019-12-16  09:03 PM               144 Cargo.lock
2019-12-16  09:02 PM                49 Cargo.toml
2019-12-16  09:02 PM    <DIR>          crates
               3 File(s)            212 bytes
               4 Dir(s)  995,853,742,080 bytes free

D:\repos\cad97\pointer-utils>type Cargo.toml
[workspace]
members = [
    "crates/erasable",
]

D:\repos\cad97\pointer-utils>cargo crev crate verify
status reviews     downloads    owner  issues lines  geiger flgs crate                version         latest_t
thread '<unnamed>' panicked at 'Unable to scan crate: NotFound

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <crates_io_api::types::Owners as cargo_crev::crates_io::Cacheable>::fetch
   5: cargo_crev::crates_io::Client::new
   6: cargo_crev::crates_io::Client::get_owners
   7: cargo_crev::deps::scan::Scanner::get_crate_details
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::panicking::try::do_call
  10: panic_unwind::__rust_maybe_catch_panic
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libpanic_unwind\lib.rs:78
  11: core::mem::drop
  12: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\liballoc\boxed.rs:942
  13: alloc::boxed::{{impl}}::call_once
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\liballoc\boxed.rs:942
  14: std::sys_common::thread::start_thread
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\thread.rs:13
  15: std::sys::windows::thread::{{impl}}::new::thread_start
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys\windows\thread.rs:47
  16: BaseThreadInitThunk
  17: RtlUserThreadStart
', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:468
  10: std::panicking::continue_panic_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\panicking.rs:139
  13: core::result::unwrap_failed
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\result.rs:1165
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

At this point, cargo-crev hangs indefinitely. I'm using cargo-crev 0.14.0 from crates-io. Running on Windows, but I expect the behavior to be OS-independent.

This workspace does not currently have any dependencies. If I add one, I get:

```cmd
D:\repos\cad97\pointer-utils>cargo crev crate verify
status reviews     downloads    owner  issues lines  geiger flgs crate                version         latest_t
none    1  5  1266905   6736578  2/2    0/0     530       0      either               1.5.3           ↓1.5.2
thread '<unnamed>' panicked at 'Unable to scan crate: NotFound
[...]
```

This applies to running `cargo crev crate verify` in actual crates as well.

**Comment by CAD97** [comment]
Here's a backtrace with cargo-crev built in debug mode:

```cmd
D:\repos\cad97\pointer-utils>cargo crev crate verify
status reviews     downloads    owner  issues lines  geiger flgs crate                version         latest_t
none    1  5  1266905   6736578  2/2    0/0     530       0      either               1.5.3           ↓1.5.2
thread '<unnamed>' panicked at 'Unable to scan crate: NotFound

stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized<closure-0>
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<closure-0>
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\capture.rs:164
   4: backtrace::capture::Backtrace::new_unresolved
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\capture.rs:158
   5: failure::backtrace::internal::InternalBacktrace::new
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.6\src\backtrace\internal.rs:46
   6: failure::backtrace::Backtrace::new
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.6\src\backtrace\mod.rs:121
   7: failure::error::error_impl::{{impl}}::from<crates_io_api::Error>
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.6\src\error\error_impl.rs:19
   8: failure::error::{{impl}}::from<crates_io_api::Error>
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.6\src\error\mod.rs:36
   9: cargo_crev::crates_io::{{impl}}::fetch
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\crates_io.rs:42
  10: cargo_crev::crates_io::Client::fetch<crates_io_api::types::Owners>
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\crates_io.rs:97
  11: cargo_crev::crates_io::Client::get<crates_io_api::types::Owners>
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\crates_io.rs:115
  12: cargo_crev::crates_io::Client::get_owners
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\crates_io.rs:127
  13: cargo_crev::deps::scan::Scanner::get_crate_details
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\deps\scan.rs:289
  14: cargo_crev::deps::scan::{{impl}}::run::{{closure}}::{{closure}}
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\deps\scan.rs:193
  15: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}<cargo::core::package_id::PackageId,closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:628
  16: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}<(),cargo::core::package_id::PackageId,closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:1828
  17: core::iter::traits::iterator::Iterator::try_fold<crossbeam_channel::channel::IntoIter<cargo::core::package_id::PackageId>,(),closure-0,core::result::Result<(), !>>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:1709
  18: core::iter::traits::iterator::Iterator::fold<crossbeam_channel::channel::IntoIter<cargo::core::package_id::PackageId>,(),closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:1831
  19: core::iter::traits::iterator::Iterator::for_each<crossbeam_channel::channel::IntoIter<cargo::core::package_id::PackageId>,closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:631
  20: cargo_crev::deps::scan::{{impl}}::run::{{closure}}
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\deps\scan.rs:175
  21: std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,()>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libstd\sys_common\backtrace.rs:129
  22: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,()>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libstd\thread\mod.rs:469
  23: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libstd\panic.rs:317
  24: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libstd\panicking.rs:287
  25: panic_unwind::__rust_maybe_catch_panic
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libpanic_unwind\lib.rs:78
  26: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libstd\panicking.rs:265
  27: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libstd\panic.rs:396
  28: std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,()>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libstd\thread\mod.rs:468
  29: core::ops::function::FnOnce::call_once<closure-0,()>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\ops\function.rs:227
  30: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\liballoc\boxed.rs:942
  31: alloc::boxed::{{impl}}::call_once
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\liballoc\boxed.rs:942
  32: std::sys_common::thread::start_thread
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\thread.rs:13
  33: std::sys::windows::thread::{{impl}}::new::thread_start
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys\windows\thread.rs:47
  34: BaseThreadInitThunk
  35: RtlUserThreadStart
', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:468
  10: std::panicking::continue_panic_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\panicking.rs:139
  13: core::result::unwrap_failed
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\result.rs:1165
  14: core::result::Result<cargo_crev::deps::CrateDetails, failure::error::Error>::expect<cargo_crev::deps::CrateDetails,failure::error::Error>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\result.rs:960
  15: cargo_crev::deps::scan::{{impl}}::run::{{closure}}::{{closure}}
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\deps\scan.rs:193
  16: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}<cargo::core::package_id::PackageId,closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:628
  17: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}<(),cargo::core::package_id::PackageId,closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:1828
  18: core::iter::traits::iterator::Iterator::try_fold<crossbeam_channel::channel::IntoIter<cargo::core::package_id::PackageId>,(),closure-0,core::result::Result<(), !>>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:1709
  19: core::iter::traits::iterator::Iterator::fold<crossbeam_channel::channel::IntoIter<cargo::core::package_id::PackageId>,(),closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:1831
  20: core::iter::traits::iterator::Iterator::for_each<crossbeam_channel::channel::IntoIter<cargo::core::package_id::PackageId>,closure-0>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\libcore\iter\traits\iterator.rs:631
  21: cargo_crev::deps::scan::{{impl}}::run::{{closure}}
             at D:\.rust\cargo\registry\src\github.com-1ecc6299db9ec823\cargo-crev-0.14.0\src\deps\scan.rs:175
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by CAD97** [comment]
Culprit appears to be this line, which IIUC fails on virtual manifests:

https://github.com/crev-dev/cargo-crev/blob/2e39dca4a0f5fbde54e3338221a9bb2f4e46c569/cargo-crev/src/deps/scan.rs#L289

I think the simple solution is to skip the owners check for local crates, as it doesn't make too much sense anyway.

**Comment by dpc** [comment]
Weird, because `cargo-crev` lives in the workspace, and that's where I mostly test it. Works here.

Can you `dbg!(...)` on that `&pkg_name` there?

Thanks for reporting it! I've decided to include local crates in the output, and unify the processing and now there's a lot of follow-up issues with it.

**Comment by CAD97** [comment]
```cmd
status reviews     downloads    owner  issues lines  geiger flgs crate                version         latest_t
[cargo-crev\src\deps\scan.rs:289] &pkg_name = "erasable"
[cargo-crev\src\deps\scan.rs:289] &pkg_name = "erasable"
thread '<unnamed>' panicked at 'Unable to scan crate: NotFound

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <crates_io_api::types::Owners as cargo_crev::crates_io::Cacheable>::fetch
   5: cargo_crev::crates_io::Client::new
   6: cargo_crev::crates_io::Client::get_owners
   7: cargo_crev::deps::scan::Scanner::get_crate_details
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::panicking::try::do_call
  10: panic_unwind::__rust_maybe_catch_panic
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libpanic_unwind\lib.rs:78
  11: core::mem::drop
  12: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\liballoc\boxed.rs:942
  13: alloc::boxed::{{impl}}::call_once
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\liballoc\boxed.rs:942
  14: std::sys_common::thread::start_thread
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\thread.rs:13
  15: std::sys::windows::thread::{{impl}}::new::thread_start
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys\windows\thread.rs:47
  16: BaseThreadInitThunk
  17: RtlUserThreadStart
', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:468
  10: std::panicking::continue_panic_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\panicking.rs:139
  13: core::result::unwrap_failed
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\result.rs:1165
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'Unable to scan crate: NotFound

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <crates_io_api::types::Owners as cargo_crev::crates_io::Cacheable>::fetch
   5: cargo_crev::crates_io::Client::new
   6: cargo_crev::crates_io::Client::get_owners
   7: cargo_crev::deps::scan::Scanner::get_crate_details
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::panicking::try::do_call
  10: panic_unwind::__rust_maybe_catch_panic
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libpanic_unwind\lib.rs:78
  11: core::mem::drop
  12: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\liballoc\boxed.rs:942
  13: alloc::boxed::{{impl}}::call_once
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\src\liballoc\boxed.rs:942
  14: std::sys_common::thread::start_thread
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\thread.rs:13
  15: std::sys::windows::thread::{{impl}}::new::thread_start
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys\windows\thread.rs:47
  16: BaseThreadInitThunk
  17: RtlUserThreadStart
', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:468
  10: std::panicking::continue_panic_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\panicking.rs:139
  13: core::result::unwrap_failed
             at /rustc/edff4c8b40c778ab40a74324e750217ff704113a\/src\libcore\result.rs:1165
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Wait... it's because the crate isn't published to crates-io yet! (Local crates need to look at the local information, not the crates-io information, I guess.)

```powershell
PS D:\repos\cad97> cargo new --lib this-is-not-published
     Created library `this-is-not-published` package
PS D:\repos\cad97> cd .\this-is-not-published\
PS D:\repos\cad97\this-is-not-published> cargo build
   Compiling this-is-not-published v0.1.0 (D:\repos\cad97\this-is-not-published)
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
PS D:\repos\cad97\this-is-not-published> cargo crev crate verify
status reviews     downloads    owner  issues lines  geiger flgs crate                version         latest_t
[cargo-crev\src\deps\scan.rs:289] &pkg_name = "this-is-not-published"
thread '<unnamed>' panicked at 'Unable to scan crate: NotFound
[...]
```

**Comment by dpc** [comment]
Yeah. That's more like it. :)

I'll get to it at some point, but if you feel adventurous, just make this field an `Option`, fix the places that want to use it (default to zero or `-` or something?) and submit a PR! :)

**Comment by dpc** [comment]
I think we should probably not fail/panic if `crates_io` fails one way or another.
