### ISSUE TITLE
cargo crev crate verify panics 

### ISSUE THREAD

**Issue by 0xd34b33f** [crev-dev/cargo-crev#279]
Linux  5.4.6-2-MANJARO
 cargo-crev 0.14.0
Installed with cargo install
```
thread '<unnamed>' panicked at 'Unable to scan crate: NotFound

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: <crates_io_api::types::Owners as cargo_crev::crates_io::Cacheable>::fetch
   3: cargo_crev::crates_io::Client::fetch
   4: cargo_crev::crates_io::Client::get_owners
   5: cargo_crev::deps::scan::Scanner::get_crate_details
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::panicking::try::do_call
   8: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/liballoc/boxed.rs:1015
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  12: start_thread
  13: clone
', src/libcore/result.rs:1192:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:467
  11: rust_begin_unwind
             at src/libstd/panicking.rs:371
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1192
```

**Comment by dpc** [comment]
I think this might be fixed on master.

**Comment by 0xd34b33f** [comment]
Reinstalled from git and it works
