### ISSUE TITLE
Test failure with creates_new_id_implicitly

### ISSUE THREAD

**Issue by kpcyrd** [crev-dev/cargo-crev#402]
There's a failing test starting with 0.20.0 on Arch Linux:
```
% RUST_BACKTRACE=1 cargo test
[...]
---- creates_new_id_implicitly stdout ----
thread 'creates_new_id_implicitly' panicked at 'assertion failed: c.run(&[\"id\", \"trust\", \"--level=medium\",\n        \"FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE\"], \"\").status.success()', cargo-crev/tests/clitest.rs:11:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
   3: clitest::creates_new_id_implicitly
             at ./tests/clitest.rs:11:5
   4: clitest::creates_new_id_implicitly::{{closure}}
             at ./tests/clitest.rs:7:1
   5: core::ops::function::FnOnce::call_once
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dpc** [comment]
Can't reproduce. Was this a one time thing or it happens every time? It might be some local problem or some assumption somewhere that doesn't work on your system. :thinking:

**Comment by dpc** [comment]
If you want to help me debug this (if it persistent), find the line like this:


```
Running tests/clitest.rs (target/debug/deps/clitest-7b973c51747d6f21)
```

Then run that test standalone like this:

```
 strace -fff target/debug/deps/clitest-7b973c51747d6f21
```

If you can provide me with this `strace` output, I might be able to figure out what is going wrong and where.
